version: "3.8"

services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - "--path.rootfs=/host"
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - "/:/host:ro,rslave"
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    privileged: true
    container_name: homeassistant
    ports:
      - 8123:8123
    restart: unless-stopped
    volumes:
      - ./homeassistant:/config
      - /run/dbus:/run/dbus:ro
      - /etc/localtime:/etc/localtime:ro
    # network_mode: host
  wyoming-piper:
    image: rhasspy/wyoming-piper
    container_name: wyoming-piper
    ports:
      - 10200:10200
    restart: unless-stopped
    command: "--voice en_US-lessac-medium"
  wyoming-whisper:
    image: rhasspy/wyoming-whisper
    container_name: wyoming-whisper
    ports:
      - 10300:10300
    restart: unless-stopped
    command: "--model tiny-int8 --language en"
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    depends_on:
      - cadvisor
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
  cadvisor:
    image: zcube/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    depends_on:
      - redis
    restart: unless-stopped
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    restart: unless-stopped
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=boom
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    restart: unless-stopped
  nats-server:
    image: nats:latest
    container_name: nats-server
    command: "-c /etc/nats/nats.conf --http_port 8222 -js"
    restart: unless-stopped
    volumes:
      - ./nats.conf:/etc/nats/nats.conf
    ports:
      - 4222:4222
      # - 6222:6222
      - 8222:8222
  nats-exporter:
    image: natsio/prometheus-nats-exporter:latest
    container_name: nats-exporter
    restart: unless-stopped
    depends_on:
      - nats-server
    ports:
      - 7778:7777
    command: "-connz -varz -channelz -serverz -subz -jsz=all http://nats-server:8222"
  nats-box:
    image: natsio/nats-box:latest
    container_name: nats-box
    restart: unless-stopped
    tty: true
    depends_on:
      - nats-server

volumes:
  prometheus_data:
  grafana_data:
