version: "3.8"
# docker-compose -f monitoring.yaml up -d

services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - "--path.rootfs=/host"
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - "/:/host:ro,rslave"
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    depends_on:
      - cadvisor
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
  cadvisor:
    image: zcube/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    depends_on:
      - redis
    restart: unless-stopped
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    restart: unless-stopped
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=boom
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  prometheus_data:
  grafana_data:
# https://prometheus.io/docs/guides/node-exporter/
# https://prometheus.io/docs/guides/cadvisor/#monitoring-docker-container-metrics-using-cadvisor
# https://thesmarthomejourney.com/2022/07/25/monitoring-smarthome-prometheus/

# dashboards https://grafana.com/grafana/dashboards/14282-cadvisor-exporter/
# https://grafana.com/grafana/dashboards/1860-node-exporter-full/
# https://grafana.com/grafana/dashboards/15172-node-exporter-for-prometheus-dashboard-based-on-11074/
# https://grafana.com/grafana/dashboards/3662-prometheus-2-0-overview/
