# docker-compose -f nats-cluster.yaml up -d
version: "3.8"
services:
  nats:
    image: nats
    ports:
      - "8222:8222"
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222 "
    networks: ["nats"]
  nats-1:
    image: nats
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks: ["nats"]
    depends_on: ["nats"]
  nats-2:
    image: nats
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks: ["nats"]
    depends_on: ["nats"]
  nats-box:
    image: natsio/nats-box
    networks: ["nats"]
    depends_on: ["nats"]
  nats-exporter:
    image: natsio/nats-exporter
    networks: ["nats"]
    depends_on: ["nats"]
    ports:
      - "7777:7777"
networks:
  nats:
    name: nats
# https://docs.nats.io/running-a-nats-service/nats_docker
# https://github.com/bmcustodio/docker-compose-nats-cluster/blob/master/README.md
