scrape_configs:
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
    - targets: ['cadvisor:8080']
- job_name: 'prometheus'
  static_configs:
    - targets: ['localhost:9090']
- job_name: 'node-exporter'
  static_configs:
    - targets: ['host.docker.internal:9100']
- job_name: 'nats-exporter'
  static_configs:
    - targets: ['nats-exporter:7777']